services:
  UMAT_2scale_LSDYNA:
    build: .
    image: my_umat_lsdyna_image
    container_name: my_umat_lsdyna_container
    environment:
      - DISPLAY=${DISPLAY}  # docker run -e DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix  # docker run -v /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri:/dev/dri  # docker run -v /dev/dri:/dev/dri
      - ./:/workspaces/UMAT_2scale_LSDYNA # mount current dir to /workspaces/UMAT_2scale_LSDYNA
    network_mode: host  # docker run --net=host
    ipc: host  # docker run --ipc=host
    entrypoint: ["/bin/bash"]
    stdin_open: true  # docker run -i
    tty: true  # docker run -t
