version: "3"

services:
  umat_2scale_lsdyna:
    image: umat_2scale_lsdyna
    build: .
    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /dev/dri:/dev/dri
    network_mode: host
    ipc: host
    tty: true
