--- lsdyna_object_version_ref/Makefile	2020-09-03 20:57:17.000000000 +0200
+++ lsdyna_object_version/Makefile	2021-08-16 12:30:06.405213200 +0200
@@ -10,13 +10,15 @@
 # below. Example:
 # LMATH=
 #
-FC=/opt/intel/compilers_and_libraries_2016/linux/bin/intel64/ifort -qopenmp
+CC = icc
+FC=ifort -g -fpe0 -traceback -debug extended -qopenmp
 #
-FF=-safe_cray_ptr -assume byterecl,buffered_io,protect_parens -warn nousage -zero -ftz -fp-model precise -mP2OPT_hpo_dist_factor=21 -diag-disable 10212,10010 -fimf-arch-consistency=true -qno-opt-dynamic-align -xSSE2 -align array16byte -nopad -qopenmp -i8 -r8 -fPIC -O2
+FF=-safe-cray-ptr -assume byterecl,buffered_io,protect_parens -warn nousage -zero -ftz -fp-model precise -mP2OPT_hpo_dist_factor=21 -diag-disable 10212,10010 -fimf-arch-consistency=true -qno-opt-dynamic-align -align array16byte -nopad -qopenmp -i8 -r8 -fPIC -O3 -march=native -mtune=native
 #
-LD=/opt/intel/compilers_and_libraries_2016/linux/bin/intel64/ifort -qopenmp -sox
+LD=ifort -g -fpe0 -traceback -debug extended -qopenmp -sox
 #
 LF= -static-intel -L/usr/X11R6/lib64 -lX11 -qopenmp -lrt -lstdc++ -lpthread -lstdc++ -lpthread
+LFpython= -L/usr/lib/python3.8/config-3.8-x86_64-linux-gnu -L/usr/lib -lpython3.8 -lcrypt -lpthread -ldl  -lutil -lm -lm 
 #
 #LMATH= liblapack.a libblas.a
 LMATH= libmkl_intel_ilp64.a libmkl_intel_thread.a libmkl_core.a
@@ -26,10 +28,25 @@
 #
 LIBS=libdyna.a libbcsext4.a liblsda.a liblsdb.a liblssecurity.a  liblcpack.a libspooles.a libcparse.a libmf2.a liblsm.a liblscrypt.a libresurf.a libdsa.a libsfg.a libevl.a  libcminpack.a  libzmumps.a libdmumps.a libmumps_common.a libmumps_mpiseq.a    libmetis.a libim_rotor_dynamics.a libarpack.a  libmcms.a   liblso.a libunits.a  libem.a libfemster_wrap.a libfemster_wrap2d.a libfemster_wrap1d.a libfemster.a libfemster2d.a libfemster1d.a libpfem.a libcese.a libchemistry.a libparticles.a libeosfl2.a  libpfem.a libmoving.a libdualcese.a libbattery.a libfftw3.a  libansysl.a   libdyna.a libmetis.a libspooles.a
 #
-lsdyna: $(OBJS)
+UMAT=forpy_mod.o include_ttb.o umat_elastic_43_13.o umat_elastic_44_14.o umat.o umat_cpp_call_py.o
+lsdyna: rve/dae_rve_2d.f rve/dae_rve_3d.f rve/daeblk.f $(UMAT) $(OBJS)
 	set PATH=.:$(PATH)
-	$(LD) -o lsdyna $(OBJS) $(LIBS) $(LMATH) $(LMATH) $(LMATH)  $(LF)
-#
+	$(LD) -o lsdynaumat $(UMAT) $(OBJS) $(LIBS) $(LMATH) $(LMATH) $(LMATH)  $(LF) $(LFpython) -L/usr/lib/x86_64-linux-gnu/hdf5/serial/ -lhdf5 -Irve -Iexternal_packages
+clean :
+	-rm -rf $(UMAT) init_dyn21.o userinterface.o dyn21.o dyn21umat.o dyn21umats.o dyn21umatv.o dyn21umatc.o dyn21tumat.o dyn21utan.o dyn21ueos.o dyn21cnt.o dyn21ushl.o dyn21usld.o couple2other_user.o dynrfn_user.o test.o *.mod lsdyna
+umat.o : umat/umat.cpp   
+	$(CC) -Wall -c -O3 -march=native -mtune=native umat/umat.cpp -Iexternal_packages -I/usr/include/hdf5/serial/ -L/usr/lib/x86_64-linux-gnu/hdf5/serial/ -lhdf5
+umat_cpp_call_py.o : umat/umat_cpp_call_py.cpp   
+	$(CC) -Wall -c -O3 -march=native -mtune=native umat/umat_cpp_call_py.cpp -I/opt/intel/oneapi/intelpython/python3.7/include/python3.7m/ -I/home/alameddin/.dontsync/packages/intel/oneapi/intelpython/python3.7/include/python3.7m/
+include_ttb.o: external_packages/include_ttb.F
+	$(FC) -c $(FF) -I. external_packages/include_ttb.F
+forpy_mod.o: external_packages/forpy_mod.F90
+	$(FC) -c -I. external_packages/forpy_mod.F90
+umat_elastic_43_13.o: umat/umat_elastic_43_13.F90
+	$(FC) -c $(FF) -I. umat/umat_elastic_43_13.F90
+umat_elastic_44_14.o: umat/umat_elastic_44_14.F90
+	$(FC) -c $(FF) -I. umat/umat_elastic_44_14.F90
+
 init_dyn21.o: init_dyn21.f nhisparm.inc
 	$(FC) -c $(FF) -I. init_dyn21.f
 userinterface.o: userinterface.f90
